# Generated by Django 3.2.7 on 2021-10-04 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_published', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
